name: CI

on:
  push:
    branches:
      - main

jobs:
  get_asdf_version:
    name: Get asdf Version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_asdf_version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        name: Checkout source code

      - name: Get asdf version
        id: get_asdf_version
        uses: ./.github/actions/get_asdf_version

  quality_checks:
    name: Quality Checks
    needs: get_asdf_version
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks.yml@d215f841eb18b803e339e4ed597ed1f30e086e17
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.version }}
      reinstall_poetry: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
