name: CI

on:
  push:
    branches:
      - main

jobs:
  get_asdf_version:
    name: Get asdf Version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_asdf_version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        name: Checkout source code

      - name: Get asdf version
        id: get_asdf_version
        uses: ./.github/actions/get_asdf_version

  quality_checks:
    name: Quality Checks
    needs: get_asdf_version
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks.yml@9791a77de7b005056b4ddfb9789306f5179f53da
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.version }}
      reinstall_poetry: true
      run_sonar: false
