name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  pr_title_format_check:
    name: PR Title Format Check
    uses: NHSDigital/eps-common-workflows/.github/workflows/pr_title_check.yml@8404cf6e3a61ac8de4d1644e175e288aa4965815

  get_asdf_version:
    name: Get asdf Version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_asdf_version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        name: Checkout source code

      - name: Get asdf version
        id: get_asdf_version
        uses: ./.github/actions/get_asdf_version

  quality_checks:
    name: Quality Checks
    needs: get_asdf_version
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks.yml@8404cf6e3a61ac8de4d1644e175e288aa4965815
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.version }}
      reinstall_poetry: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tag_release:
    name: Tag Release (Dry Run)
    needs: get_asdf_version
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release.yml@8404cf6e3a61ac8de4d1644e175e288aa4965815
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.version }}
      branch_name: ${{ github.event.pull_request.head.ref }}
      dry_run: true

  dependabot_auto_approve_and_merge:
    name: Dependabot Auto Approve and Merge
    needs: quality_checks
    uses: NHSDigital/eps-common-workflows/.github/workflows/dependabot-auto-approve-and-merge.yml@8404cf6e3a61ac8de4d1644e175e288aa4965815
    secrets:
      AUTOMERGE_APP_ID: ${{ secrets.AUTOMERGE_APP_ID }}
      AUTOMERGE_PEM: ${{ secrets.AUTOMERGE_PEM }}

  build:
    name: Build Package and Perform Test Publish
    runs-on: ubuntu-22.04
    needs: [get_asdf_version, tag_release, quality_checks]
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies
        with:
          asdf_version: ${{ needs.get_asdf_version.outputs.version }}

      - name: Get latest version
        id: get_latest_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "version_tag=${latest_tag#v}" >> "$GITHUB_OUTPUT"

      - name: Build package
        run: |
          poetry version "${LATEST_VERSION}.${PR_NUMBER}"
          make build
          cd dist
          zip -r eps_spine_shared.zip ./*
        env:
          LATEST_VERSION: ${{ steps.get_latest_version.outputs.version_tag }}
          PR_NUMBER: ${{ github.event.number }}

      - name: poetry config
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/

      - name: poetry test publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
