name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  pr_title_format_check:
    name: PR Title Format Check
    uses: NHSDigital/eps-common-workflows/.github/workflows/pr_title_check.yml@9791a77de7b005056b4ddfb9789306f5179f53da

  get_asdf_version:
    name: Get asdf Version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_asdf_version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        name: Checkout source code

      - name: Get asdf version
        id: get_asdf_version
        uses: ./.github/actions/get_asdf_version

  quality_checks:
    name: Quality Checks
    needs: get_asdf_version
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks.yml@9791a77de7b005056b4ddfb9789306f5179f53da
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.version }}
      reinstall_poetry: true
      run_sonar: false

  tag_release:
    name: Tag Release (Dry Run)
    needs: get_asdf_version
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release.yml@9791a77de7b005056b4ddfb9789306f5179f53da
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.version }}
      branch_name: ${{ github.event.pull_request.head.ref }}
      dry_run: true
      publish_package: false

  dependabot_auto_approve_and_merge:
    name: Dependabot Auto Approve and Merge
    needs: quality_checks
    uses: NHSDigital/eps-common-workflows/.github/workflows/dependabot-auto-approve-and-merge.yml@9791a77de7b005056b4ddfb9789306f5179f53da
    secrets:
      AUTOMERGE_APP_ID: ${{ secrets.AUTOMERGE_APP_ID }}
      AUTOMERGE_PEM: ${{ secrets.AUTOMERGE_PEM }}
