name: Release

on:
  workflow_dispatch:

jobs:
  get_asdf_version:
    name: Get asdf Version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get-asdf-version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        name: Checkout source code

      - name: Get asdf version
        id: get-asdf-version
        uses: ./.github/actions/get_asdf_version

  tag_release:
    name: Tag Release
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release.yml@3cba6a3733673bafc95526503478674332c26007
    needs: get_asdf_version
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.version }}
      branch_name: main
      dry_run: false
      publish_package: false

  release:
    name: Upload Package to GitHub Release
    needs: [get_asdf_version, tag_release]
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies
        with:
          asdf_version: ${{ needs.get_asdf_version.outputs.version }}

      - name: Build package
        run: make build

      - name: Upload package to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.tag_release.outputs.version_tag }} dist/* --clobber
