name: Release

on:
  workflow_dispatch:

jobs:
  get_asdf_version:
    name: Get asdf Version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get-asdf-version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        name: Checkout source code

      - name: Get asdf version
        id: get-asdf-version
        uses: ./.github/actions/get_asdf_version

  build:
    name: Build Package and Upload as Artifact
    runs-on: ubuntu-22.04
    needs: get_asdf_version
    outputs:
      artifact_id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies
        with:
          asdf_version: ${{ needs.get_asdf_version.outputs.version }}

      - name: Build package
        run: |
          make build
          cd dist
          zip -r package.zip ./*

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: eps_spine_shared
          path: |
            dist/package.zip

  tag_release:
    name: Tag Release
    uses: NHSDigital/eps-common-workflows/.github/workflows/tag-release.yml@3cba6a3733673bafc95526503478674332c26007
    needs: [build, get_asdf_version]
    with:
      asdfVersion: ${{ needs.get_asdf_version.outputs.version }}
      branch_name: main
      extra_artifact_name: eps_spine_shared.zip
      extra_artifact_id: ${{ needs.build.outputs.artifact_id }}
      extra_artifact_run_id: ${{ github.run_id }}
      extra_artifact_repository: ${{ github.repository }}
      dry_run: false
      publish_package: false
